name: XVir
channels:
  - defaults
dependencies:
  - keras==3.3.3
  - matplotlib==3.7.0
  - numpy==1.23.5
  - pandas==1.5.3
  - scikit_learn==1.2.1
  - scipy==1.10.0
  - tensorflow==2.16.1
  - tflearn==0.5.0
  - torch==1.12.1
  - tqdm==4.64.1